server:
#  port: 8080
  error:
    whitelabel:
      enabled: false
    path: /error
  servlet:
    session:
      timeout: 2m
      cookie:
        http-only: true
        secure: true
spring:
  application:
    name: SCM
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/contactmanager
#    username: root
#    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-black-snowflake-30567558.us-east-2.aws.neon.tech/ContactManager_DB
    username: gkalyankar33
    password: 1dPanL2MHkqB
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: -1
  security:
    oauth2:
      client:
        registration:
         facebook:
          clientId: 742312823799469
          clientSecret: e4f05e32b7c846328b2c59d9d09c9828
          scope:
           - email
           - public_profile
         google:
          clientId: 282997076007-qbc2j46arkc5ak9pcffif8gihmdocuib.apps.googleusercontent.com
          clientSecret: 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
          scope:
           - https://www.googleapis.com/auth/userinfo.email
           - https://www.googleapis.com/auth/userinfo.profile
         github:
          clientId: 4c50b06fc357bc45a730
          clientSecret: 2bb9d40b698e890f62448fd7ca2fb2e24774edf4
          scope:
           - user:email
           - read:user
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ssmartcontactmanager@gmail.com
    password: qofvffvgrtmslaku
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp: 
          auth: true
          starttls:
            enable: true